In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
# Load data
df = pd.read_csv(r"D:\DATA ANALYSIS\Meta Ads Campaign Performance Analysis\Data\Raw\Meta_Ads_Dataset.csv")

In [4]:
df

,campaign_id,campaign_name,adset,platform,objective,status,start_date,end_date,impressions,reach,...,purchases,revenue,conversion_value,country,region,age_group,gender,placement,device,creative_type
0,C027,Hyderabad Conversion,Interest - Technology,Facebook,Leads,COMPLETED,2026-02-18,2026-02-25,83426,68019,...,2,2508.48,2508.48,India,Hyderabad,45-54,Female,Reels,Mobile,Video
1,C055,Ahmedabad Sales,Lookalike 1%,Instagram,Leads,PAUSED,2026-04-18,2026-05-06,107945,72764,...,8,1157.30,1157.30,India,Ahmedabad,35-44,All,Audience Network,Mobile,Image
2,C050,Jaipur Lead Generation,Interest - Technology,INSTAGRAM,Conversions,active,2026-01-14,2026-02-10,14694,13073,...,0,6833.65,6833.65,India,Jaipur,18-24,Female,Instagram Feed,Mobile,Image
3,C093,Mumbai Sales,Interest - Technology,Facebook,Leads,ACTIVE,2026-04-25,2026-05-22,230437,198773,...,46,4675.25,4675.25,India,Mumbai,18-24,All,Audience Network,Mobile,Reel
4,C151,mumbai sales,Interest - Business,Instagram,Leads,PAUSED,2026-01-15,2026-02-12,239711,197146,...,24,3956.57,3956.57,India,Mumbai,55+,Female,Facebook Feed,Mobile,Reel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,C202,Pune Education,Lookalike 1%,Instagram,Sales,PAUSED,2026-02-27,2026-03-07,228309,165885,...,6,2167.72,2167.72,India,Pune,35-44,All,Instagram Stories,Mobile,Video
258,C169,Hyderabad Conversion,Engaged Users,Instagram,Traffic,PAUSED,2026-04-04,2026-05-05,159526,136594,...,26,437.30,437.30,India,Hyderabad,45-54,All,Facebook Feed,Mobile,Reel
259,C186,Hyderabad Conversion,Broad Audience,Facebook,Traffic,ACTIVE,2026-06-22,2026-07-12,50000,42394,...,13,6966.87,6966.87,India,Hyderabad,25-34,All,Facebook Feed,Mobile,Image
260,C036,Pune Education,Retargeting,Facebook,Conversions,COMPLETED,2026-05-31,2026-06-11,105814,59807,...,4,5223.31,5223.31,India,Pune,45-54,All,Facebook Stories,Mobile,Reel
261,C130,Kolkata Awareness,Interest - Business,Instagram,Conversions,PAUSED,2026-03-21,2026-04-05,135832,83336,...,8,541.65,541.65,India,Kolkata,35-44,Female,Instagram Feed,Mobile,Video

In [5]:
print(df.shape)

(262, 23)

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   campaign_id       262 non-null    object
 1   campaign_name     262 non-null    object
 2   adset             258 non-null    object
 3   platform          262 non-null    object
 4   objective         259 non-null    object
 5   status            262 non-null    object
 6   start_date        262 non-null    object
 7   end_date          262 non-null    object
 8   impressions       262 non-null    int64
 9   reach             262 non-null    int64
 10  clicks            262 non-null    int64
 11  spend             262 non-null    float64
 12  leads             262 non-null    int64
 13  purchases         262 non-null    int64
 14  revenue           262 non-null    float64
 15  conversion_value  262 non-null    float64
 16  country           262 non-null    object
 17  region            260 non-null    object
 18  age_group         262 non-null    object
 19  gender            262 non-null    object
 20  placement         259 non-null    object
 21  device            262 non-null    object
 22  creative_type     262 non-null    object
dtypes: float64(3), int64(5), object(15)
memory usage: 47.2+ KB
None

In [7]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [8]:
text_cols = ['campaign_name','adset','platform','objective','status',
             'country','region','age_group','gender','placement',
             'device','creative_type']

for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

In [9]:
df['status'] = df['status'].str.upper()

In [10]:
df

,campaign_id,campaign_name,adset,platform,objective,status,start_date,end_date,impressions,reach,...,purchases,revenue,conversion_value,country,region,age_group,gender,placement,device,creative_type
0,C027,Hyderabad Conversion,Interest - Technology,Facebook,Leads,COMPLETED,2026-02-18,2026-02-25,83426,68019,...,2,2508.48,2508.48,India,Hyderabad,45-54,Female,Reels,Mobile,Video
1,C055,Ahmedabad Sales,Lookalike 1%,Instagram,Leads,PAUSED,2026-04-18,2026-05-06,107945,72764,...,8,1157.30,1157.30,India,Ahmedabad,35-44,All,Audience Network,Mobile,Image
2,C050,Jaipur Lead Generation,Interest - Technology,Instagram,Conversions,ACTIVE,2026-01-14,2026-02-10,14694,13073,...,0,6833.65,6833.65,India,Jaipur,18-24,Female,Instagram Feed,Mobile,Image
3,C093,Mumbai Sales,Interest - Technology,Facebook,Leads,ACTIVE,2026-04-25,2026-05-22,230437,198773,...,46,4675.25,4675.25,India,Mumbai,18-24,All,Audience Network,Mobile,Reel
4,C151,Mumbai Sales,Interest - Business,Instagram,Leads,PAUSED,2026-01-15,2026-02-12,239711,197146,...,24,3956.57,3956.57,India,Mumbai,55+,Female,Facebook Feed,Mobile,Reel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,C202,Pune Education,Lookalike 1%,Instagram,Sales,PAUSED,2026-02-27,2026-03-07,228309,165885,...,6,2167.72,2167.72,India,Pune,35-44,All,Instagram Stories,Mobile,Video
258,C169,Hyderabad Conversion,Engaged Users,Instagram,Traffic,PAUSED,2026-04-04,2026-05-05,159526,136594,...,26,437.30,437.30,India,Hyderabad,45-54,All,Facebook Feed,Mobile,Reel
259,C186,Hyderabad Conversion,Broad Audience,Facebook,Traffic,ACTIVE,2026-06-22,2026-07-12,50000,42394,...,13,6966.87,6966.87,India,Hyderabad,25-34,All,Facebook Feed,Mobile,Image
260,C036,Pune Education,Retargeting,Facebook,Conversions,COMPLETED,2026-05-31,2026-06-11,105814,59807,...,4,5223.31,5223.31,India,Pune,45-54,All,Facebook Stories,Mobile,Reel
261,C130,Kolkata Awareness,Interest - Business,Instagram,Conversions,PAUSED,2026-03-21,2026-04-05,135832,83336,...,8,541.65,541.65,India,Kolkata,35-44,Female,Instagram Feed,Mobile,Video

In [11]:
#Fix Date Columns

In [12]:
def parse_date(x):
    for fmt in ('%Y-%m-%d','%Y/%m/%d','%m-%d-%Y','%d/%m/%Y'):
        try:
            return pd.to_datetime(x, format=fmt)
        except:
            continue
    return pd.NaT

df['start_date'] = df['start_date'].apply(parse_date)
df['end_date']   = df['end_date'].apply(parse_date)

In [13]:
#Handle Missing Values

In [14]:
df['region'] = df['region'].replace('Nan', np.nan)
df['objective'] = df['objective'].replace('', np.nan)

In [15]:
print(df.isnull().sum())

campaign_id         0
campaign_name       0
adset               0
platform            0
objective           0
status              0
start_date          0
end_date            0
impressions         0
reach               0
clicks              0
spend               0
leads               0
purchases           0
revenue             0
conversion_value    0
country             0
region              3
age_group           0
gender              0
placement           0
device              0
creative_type       0
dtype: int64

In [16]:
df[df['region'].isnull()]

,campaign_id,campaign_name,adset,platform,objective,status,start_date,end_date,impressions,reach,...,purchases,revenue,conversion_value,country,region,age_group,gender,placement,device,creative_type
127,C154,Mumbai Sales,Broad Audience,Facebook,Conversions,PAUSED,2026-06-18,2026-07-05,240292,175950,...,7,987.48,987.48,India,NaN,55+,All,Reels,Mobile,Video
203,C124,Jaipur Lead Generation,Broad Audience,Instagram,Traffic,ACTIVE,2026-01-31,2026-02-23,42630,37704,...,3,1116.34,1116.34,India,NaN,25-34,All,Facebook Feed,Mobile,Carousel
206,C096,Mumbai Sales,Website Visitors,Facebook,Conversions,ACTIVE,2026-01-28,2026-02-12,203041,113439,...,2,599.15,599.15,India,NaN,35-44,All,Reels,Mobile,Video

In [17]:
#Remove Duplicates

In [18]:
df = df.drop_duplicates(subset='campaign_id', keep='first')

In [19]:
#Fix Numeric Types

In [20]:
#First look at the data

In [21]:
num_cols = ['impressions','reach','clicks','spend','leads',
            'purchases','revenue','conversion_value']
df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')

C:\Users\Prince\AppData\Local\Temp\ipykernel_19652\3522096390.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')

In [22]:
#Create All KPIs

In [23]:
#CTR
df['CTR']  = (df['clicks'] / df['impressions']) * 100

C:\Users\Prince\AppData\Local\Temp\ipykernel_19652\3866267471.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CTR']  = (df['clicks'] / df['impressions']) * 100

In [24]:
#CPC
df['CPC']  = df['spend'] / df['clicks']

C:\Users\Prince\AppData\Local\Temp\ipykernel_19652\4079926550.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CPC']  = df['spend'] / df['clicks']

In [25]:
#CPA
df['CPA']  = df['spend'] / df['purchases'].replace(0, np.nan)

C:\Users\Prince\AppData\Local\Temp\ipykernel_19652\2735039773.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CPA']  = df['spend'] / df['purchases'].replace(0, np.nan)

In [26]:
#CVR
df['CVR']  = (df['purchases'] / df['clicks']) * 100

C:\Users\Prince\AppData\Local\Temp\ipykernel_19652\2954716918.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CVR']  = (df['purchases'] / df['clicks']) * 100

In [27]:
#CPL
df['CPL']  = df['spend'] / df['leads'].replace(0, np.nan)

C:\Users\Prince\AppData\Local\Temp\ipykernel_19652\3607574481.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CPL']  = df['spend'] / df['leads'].replace(0, np.nan)

In [28]:
#ROI
df['ROI']  = ((df['revenue'] - df['spend']) / df['spend']) * 100

C:\Users\Prince\AppData\Local\Temp\ipykernel_19652\2502295983.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ROI']  = ((df['revenue'] - df['spend']) / df['spend']) * 100

In [29]:
#ROAS
df['ROAS'] = df['revenue'] / df['spend']

C:\Users\Prince\AppData\Local\Temp\ipykernel_19652\2174492465.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ROAS'] = df['revenue'] / df['spend']

In [30]:
#Frequency
df['Frequency'] = df['impressions'] / df['reach']

C:\Users\Prince\AppData\Local\Temp\ipykernel_19652\1275439223.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Frequency'] = df['impressions'] / df['reach']

In [31]:
#Round for Readability

In [32]:
df[['CTR','CPC','CPA','CVR','CPL','ROI','ROAS','Frequency']] = \
    df[['CTR','CPC','CPA','CVR','CPL','ROI','ROAS','Frequency']].round(2)

C:\Users\Prince\AppData\Local\Temp\ipykernel_19652\51240138.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['CTR','CPC','CPA','CVR','CPL','ROI','ROAS','Frequency']] = \

In [33]:
df

,campaign_id,campaign_name,adset,platform,objective,status,start_date,end_date,impressions,reach,...,device,creative_type,CTR,CPC,CPA,CVR,CPL,ROI,ROAS,Frequency
0,C027,Hyderabad Conversion,Interest - Technology,Facebook,Leads,COMPLETED,2026-02-18,2026-02-25,83426,68019,...,Mobile,Video,0.52,7.16,1557.16,0.46,311.43,-19.45,0.81,1.23
1,C055,Ahmedabad Sales,Lookalike 1%,Instagram,Leads,PAUSED,2026-04-18,2026-05-06,107945,72764,...,Mobile,Image,0.68,7.55,691.76,1.09,307.45,-79.09,0.21,1.48
2,C050,Jaipur Lead Generation,Interest - Technology,Instagram,Conversions,ACTIVE,2026-01-14,2026-02-10,14694,13073,...,Mobile,Image,1.31,30.75,NaN,0.00,269.79,15.13,1.15,1.12
3,C093,Mumbai Sales,Interest - Technology,Facebook,Leads,ACTIVE,2026-04-25,2026-05-22,230437,198773,...,Mobile,Reel,1.17,1.93,113.44,1.70,57.98,-10.40,0.90,1.16
4,C151,Mumbai Sales,Interest - Business,Instagram,Leads,PAUSED,2026-01-15,2026-02-12,239711,197146,...,Mobile,Reel,0.87,1.63,141.01,1.16,27.97,16.91,1.17,1.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,C202,Pune Education,Lookalike 1%,Instagram,Sales,PAUSED,2026-02-27,2026-03-07,228309,165885,...,Mobile,Video,0.27,5.00,510.45,0.98,65.16,-29.22,0.71,1.38
258,C169,Hyderabad Conversion,Engaged Users,Instagram,Traffic,PAUSED,2026-04-04,2026-05-05,159526,136594,...,Mobile,Reel,0.88,1.42,77.16,1.84,14.33,-78.20,0.22,1.17
259,C186,Hyderabad Conversion,Broad Audience,Facebook,Traffic,ACTIVE,2026-06-22,2026-07-12,50000,42394,...,Mobile,Image,1.22,9.58,450.88,2.12,189.08,18.86,1.19,1.18
260,C036,Pune Education,Retargeting,Facebook,Conversions,COMPLETED,2026-05-31,2026-06-11,105814,59807,...,Mobile,Reel,0.71,8.16,1536.27,0.53,149.88,-15.00,0.85,1.77
261,C130,Kolkata Awareness,Interest - Business,Instagram,Conversions,PAUSED,2026-03-21,2026-04-05,135832,83336,...,Mobile,Video,0.89,1.52,229.01,0.66,59.10,-70.44,0.30,1.63

In [34]:
##Handle Missing Values

In [35]:
# Drop rows where key metrics are missing AND can't be imputed

In [36]:
df=df.dropna(subset=['impressions','clicks','spend'])

In [37]:
# Fill missing leads/purchases/revenue with 0

In [38]:
df['leads']    = df['leads'].fillna(0)
df['purchases']= df['purchases'].fillna(0)
df['revenue']  = df['revenue'].fillna(0)

In [39]:
# Fill missing reach with impressions
df['reach'] = df['reach'].fillna(df['impressions'])

In [40]:
print(df[['reach', 'leads', 'purchases', 'revenue']].isnull().sum())

reach        0
leads        0
purchases    0
revenue      0
dtype: int64

In [41]:
#Remove Invalid & Sentinel Values

In [42]:
df=df[(df['spend']>=0)&
    (df['revenue']>=0)&
    (df['leads']>=0)&
    (df['purchases']>=0)]

In [43]:
#Remove sentinel reach

In [44]:
df = df[df['reach'] < 10_000_000]

In [45]:
#Classification Logic (Continue / Pause / Discontinue)

In [46]:
def decision(row):
    if pd.isna(row['ROI']) or pd.isna(row['CVR']):
        return 'Review'
    if row['ROI'] > 1 and row['CVR'] > 1:
        return 'Continue'
    elif row['ROI'] > 0:
        return 'Pause'
    else:
        return 'Discontinue'

df['Decision'] = df.apply(decision, axis=1)

print(df['Decision'].value_counts())

Decision
Discontinue    168
Continue        55
Pause           34
Name: count, dtype: int64

In [47]:
#Save Cleaned Data

In [48]:
df.to_csv("D:/DATA ANALYSIS/Meta Ads Campaign Performance Analysis/Data/Cleaned files/meta_ads_cleaned.csv", index=False)
df.to_excel("D:/DATA ANALYSIS/Meta Ads Campaign Performance Analysis/Outputs/meta_ads_final_for_powerbi.xlsx", index=False)

print("Files saved ✅")

Files saved ✅

In [49]:
df

,campaign_id,campaign_name,adset,platform,objective,status,start_date,end_date,impressions,reach,...,creative_type,CTR,CPC,CPA,CVR,CPL,ROI,ROAS,Frequency,Decision
0,C027,Hyderabad Conversion,Interest - Technology,Facebook,Leads,COMPLETED,2026-02-18,2026-02-25,83426,68019,...,Video,0.52,7.16,1557.16,0.46,311.43,-19.45,0.81,1.23,Discontinue
1,C055,Ahmedabad Sales,Lookalike 1%,Instagram,Leads,PAUSED,2026-04-18,2026-05-06,107945,72764,...,Image,0.68,7.55,691.76,1.09,307.45,-79.09,0.21,1.48,Discontinue
2,C050,Jaipur Lead Generation,Interest - Technology,Instagram,Conversions,ACTIVE,2026-01-14,2026-02-10,14694,13073,...,Image,1.31,30.75,NaN,0.00,269.79,15.13,1.15,1.12,Pause
3,C093,Mumbai Sales,Interest - Technology,Facebook,Leads,ACTIVE,2026-04-25,2026-05-22,230437,198773,...,Reel,1.17,1.93,113.44,1.70,57.98,-10.40,0.90,1.16,Discontinue
4,C151,Mumbai Sales,Interest - Business,Instagram,Leads,PAUSED,2026-01-15,2026-02-12,239711,197146,...,Reel,0.87,1.63,141.01,1.16,27.97,16.91,1.17,1.22,Continue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,C202,Pune Education,Lookalike 1%,Instagram,Sales,PAUSED,2026-02-27,2026-03-07,228309,165885,...,Video,0.27,5.00,510.45,0.98,65.16,-29.22,0.71,1.38,Discontinue
258,C169,Hyderabad Conversion,Engaged Users,Instagram,Traffic,PAUSED,2026-04-04,2026-05-05,159526,136594,...,Reel,0.88,1.42,77.16,1.84,14.33,-78.20,0.22,1.17,Discontinue
259,C186,Hyderabad Conversion,Broad Audience,Facebook,Traffic,ACTIVE,2026-06-22,2026-07-12,50000,42394,...,Image,1.22,9.58,450.88,2.12,189.08,18.86,1.19,1.18,Continue
260,C036,Pune Education,Retargeting,Facebook,Conversions,COMPLETED,2026-05-31,2026-06-11,105814,59807,...,Reel,0.71,8.16,1536.27,0.53,149.88,-15.00,0.85,1.77,Discontinue
261,C130,Kolkata Awareness,Interest - Business,Instagram,Conversions,PAUSED,2026-03-21,2026-04-05,135832,83336,...,Video,0.89,1.52,229.01,0.66,59.10,-70.44,0.30,1.63,Discontinue

In [50]:
df["Decision"].eq("Continue").sum()

np.int64(55)